//! Local JSON persistence for settings and sessions.
//!
//! Layout (under the app data dir, e.g. `%APPDATA%\com.aks.clipper`):
//! ```text
//! settings.json
//! sessions/
//!     2026-09-23_16-32-10.json
//! ```
//! Every write goes to a temp file first and is then renamed over the target,
//! so a crash mid-write never leaves a truncated session file behind.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use serde::{de::DeserializeOwned, Serialize};

use crate::error::{AppError, AppResult};
use crate::models::{Session, SessionSummary, Settings};

pub fn write_json_atomic<T: Serialize>(path: &Path, value: &T) -> AppResult<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let tmp = path.with_extension("json.tmp");
    {
        let mut f = fs::File::create(&tmp)?;
        f.write_all(&serde_json::to_vec_pretty(value)?)?;
        f.sync_all()?;
    }
    fs::rename(&tmp, path)?;
    Ok(())
}

pub fn read_json<T: DeserializeOwned>(path: &Path) -> AppResult<T> {
    let bytes = fs::read(path)?;
    Ok(serde_json::from_slice(&bytes)?)
}

#[derive(Debug, Clone)]
pub struct Storage {
    root: PathBuf,
}

impl Storage {
    pub fn new(root: PathBuf) -> Self {
        Self { root }
    }

    fn settings_path(&self) -> PathBuf {
        self.root.join("settings.json")
    }

    pub fn sessions_dir(&self) -> PathBuf {
        self.root.join("sessions")
    }

    fn session_path(&self, id: &str) -> AppResult<PathBuf> {
        // Session ids are generated by us (timestamp based); reject anything
        // that could escape the sessions directory.
        if id.is_empty() || !id.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_') {
            return Err(AppError::msg(format!("Invalid session id: {id}")));
        }
        Ok(self.sessions_dir().join(format!("{id}.json")))
    }

    pub fn load_settings(&self) -> Settings {
        read_json(&self.settings_path()).unwrap_or_default()
    }

    pub fn save_settings(&self, settings: &Settings) -> AppResult<()> {
        write_json_atomic(&self.settings_path(), settings)
    }

    pub fn save_session(&self, session: &Session) -> AppResult<()> {
        write_json_atomic(&self.session_path(&session.id)?, session)
    }

    pub fn load_session(&self, id: &str) -> AppResult<Session> {
        let path = self.session_path(id)?;
        if !path.exists() {
            return Err(AppError::msg(format!("Session {id} not found")));
        }
        read_json(&path)
    }

    pub fn session_exists(&self, id: &str) -> bool {
        self.session_path(id).map(|p| p.exists()).unwrap_or(false)
    }

    pub fn delete_session(&self, id: &str) -> AppResult<()> {
        let path = self.session_path(id)?;
        if path.exists() {
            fs::remove_file(path)?;
        }
        Ok(())
    }

    /// All readable sessions, newest first. Corrupt files are skipped.
    pub fn list_sessions(&self) -> Vec<Session> {
        let Ok(entries) = fs::read_dir(self.sessions_dir()) else {
            return Vec::new();
        };
        let mut sessions: Vec<Session> = entries
            .flatten()
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|e| e == "json"))
            .filter_map(|p| read_json::<Session>(&p).ok())
            .collect();
        sessions.sort_by(|a, b| b.started_at.cmp(&a.started_at));
        sessions
    }

    pub fn list_summaries(&self) -> Vec<SessionSummary> {
        self.list_sessions().iter().map(SessionSummary::from).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::*;

    fn sample(id: &str, started_at: &str) -> Session {
        Session {
            id: id.into(),
            mode: SessionMode::Obs,
            status: SessionStatus::Active,
            started_at: started_at.into(),
            ended_at: None,
            timeline_started_at: Some(started_at.into()),
            recording_path: Some("D:/Streams/stream_2026-09-23.mkv".into()),
            duration: None,
            media: None,
            markers: vec![Marker {
                id: "abc123".into(),
                timestamp: 5234.2,
                created_at: "2026-09-23T17:58:41".into(),
                source: MarkerSource::Hotkey,
                timing: TimingSource::Obs,
                name: None,
                tag: Some("Funny".into()),
                clip_start: 5204.2,
                clip_end: 5264.2,
                exports: vec![],
            }],
        }
    }

    #[test]
    fn session_round_trip() {
        let dir = tempfile::tempdir().unwrap();
        let store = Storage::new(dir.path().to_path_buf());
        let s = sample("2026-09-23_16-32-10", "2026-09-23T16:32:10+02:00");
        store.save_session(&s).unwrap();

        assert!(dir.path().join("sessions/2026-09-23_16-32-10.json").exists());
        assert!(!dir.path().join("sessions/2026-09-23_16-32-10.json.tmp").exists());

        let loaded = store.load_session(&s.id).unwrap();
        assert_eq!(loaded.markers.len(), 1);
        assert_eq!(loaded.markers[0].timestamp, 5234.2);
        assert_eq!(loaded.markers[0].tag.as_deref(), Some("Funny"));
        assert_eq!(loaded.recording_path, s.recording_path);
    }

    #[test]
    fn session_json_uses_camel_case() {
        let dir = tempfile::tempdir().unwrap();
        let store = Storage::new(dir.path().to_path_buf());
        store.save_session(&sample("a", "2026-01-01T00:00:00Z")).unwrap();
        let raw = fs::read_to_string(dir.path().join("sessions/a.json")).unwrap();
        assert!(raw.contains("\"recordingPath\""));
        assert!(raw.contains("\"clipStart\""));
        assert!(raw.contains("\"createdAt\""));
    }

    #[test]
    fn overwrite_keeps_latest_markers() {
        let dir = tempfile::tempdir().unwrap();
        let store = Storage::new(dir.path().to_path_buf());
        let mut s = sample("a", "2026-01-01T00:00:00Z");
        store.save_session(&s).unwrap();
        s.markers.push(s.markers[0].clone());
        store.save_session(&s).unwrap();
        assert_eq!(store.load_session("a").unwrap().markers.len(), 2);
    }

    #[test]
    fn list_is_newest_first_and_skips_corrupt_files() {
        let dir = tempfile::tempdir().unwrap();
        let store = Storage::new(dir.path().to_path_buf());
        store.save_session(&sample("old", "2026-01-01T00:00:00Z")).unwrap();
        store.save_session(&sample("new", "2026-02-01T00:00:00Z")).unwrap();
        fs::write(store.sessions_dir().join("broken.json"), b"{ not json").unwrap();
        let ids: Vec<_> = store.list_sessions().into_iter().map(|s| s.id).collect();
        assert_eq!(ids, vec!["new", "old"]);
    }

    #[test]
    fn rejects_path_traversal_ids() {
        let dir = tempfile::tempdir().unwrap();
        let store = Storage::new(dir.path().to_path_buf());
        assert!(store.load_session("../settings").is_err());
        assert!(store.delete_session("..\\x").is_err());
    }

    #[test]
    fn missing_settings_fall_back_to_defaults() {
        let dir = tempfile::tempdir().unwrap();
        let store = Storage::new(dir.path().to_path_buf());
        let s = store.load_settings();
        assert_eq!(s.hotkey, "F8");
        assert_eq!(s.padding_before, 30.0);
        assert_eq!(s.obs.port, 4455);
    }

    #[test]
    fn partial_settings_file_keeps_other_defaults() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("settings.json"), br#"{ "hotkey": "F9", "obs": { "port": 4456 } }"#).unwrap();
        let s = Storage::new(dir.path().to_path_buf()).load_settings();
        assert_eq!(s.hotkey, "F9");
        assert_eq!(s.obs.port, 4456);
        assert_eq!(s.obs.host, "localhost");
        assert_eq!(s.padding_after, 30.0);
    }
}
